---

# This is a playbook for Ansible using network-engine with "ping" parser.
# Example: ansible-playbook ping.yml --extra-vars dst=192.168.0.1
# Example: ansible-playbook ping.yml --limit switch.example.com --extra-vars dst="192.168.0.1 vrf=100"

- hosts: unknown

  vars:
    vrf: ""

  roles:
  - ansible-network.network-engine

  tasks:
  - name: Run 'ping'
    ios_command:
      commands:
        - ping "{{ dst }}"
    register: output
    when: vrf is not defined

  - name: Run 'ping with vrf'
    ios_command:
      commands:
        - ping vrf "{{ vrf }}" "{{ dst }}"
    register: output
    when: vrf is defined

    #  - name: Display the output
    #    debug: var=output.stdout

  - name: Parse the output
    command_parser:
      file: "parsers/ios/ping_parser.yml"
      content: "{{ output.stdout[0] }}"

  - name: Display the data
    debug: var=ping_facts


  - name: Delete '/tmp/ping_facts-[inventory_hostname].json'
    file:
      path: "/tmp/ping_facts-{{ inventory_hostname }}.json"
      state: absent

  - name: Write ping_facts to '/tmp/ping_facts-[inventory_hostname].json'
    copy:
      content: "{{ ping_facts | to_nice_json }}"
      dest: "/tmp/ping_facts-{{ inventory_hostname }}.json"

